package core_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"atheon/core"
)

// TestQualityEnforcementPatterns tests the new quality enforcement patterns
func TestQualityEnforcementPatterns(t *testing.T) {
	// Remove local bundle override to ensure we use embedded patterns
	os.Remove(filepath.Join(os.Getenv("HOME"), ".atheon", "patterns.bundle"))

	// Create a temporary test file with various quality issues
	tmpDir := t.TempDir()
	testFile := filepath.Join(tmpDir, "test.sh")

	content := `#!/bin/bash
# Test script with various shortcuts and bypasses

git push --force origin main  # Should trigger git-force-push
git reset --hard HEAD~1        # Should trigger git-hard-reset
npm install --force            # Should trigger build-force
pip install --ignore-installed # Should trigger package-manager-force

# Skip tests
mvn install -DskipTests        # Should trigger skip-tests
npm test --skip-tests          # Should trigger skip-tests

# Insecure operations
curl --insecure https://example.com  # Should trigger insecure-flag
wget --no-check-certificate https://example.com

# Auto-confirmations
apt-get install -y package      # Should trigger auto-confirm
yes | pip install package       # Should trigger auto-confirm

# Skip hooks
git commit --no-verify -m "test"  # Should trigger skip-hooks

# Clean operations
git clean -fd                   # Should trigger git-clean-force

# AI-generated code markers
# TODO: implement this later     # Should trigger ai-safety-bypass
# Generated by AI assistant

# CI bypass
allow_failure: true            # Should trigger ci-bypass
continue-on-error: true         # Should trigger ci-bypass
`

	if err := os.WriteFile(testFile, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}

	// Enable all patterns for comprehensive testing
	core.EnableAllPatterns()

	// Scan the file
	findings, stats, err := core.ScanFile(testFile)
	if err != nil {
		t.Fatalf("ScanFile failed: %v", err)
	}

	t.Logf("Scanned %d files, found %d findings", stats.Files, len(findings))

	// Check for specific quality enforcement patterns
	qualityPatterns := []string{
		"git-force-push",
		"git-hard-reset",
		"build-force",
		"skip-tests",
		"insecure-flag",
		"auto-confirm",
		"skip-hooks",
		"git-clean-force",
		"ai-safety-bypass",
		"ci-bypass",
	}

	foundPatterns := make(map[string]bool)
	for _, finding := range findings {
		foundPatterns[finding.Pattern] = true
	}

	// Verify we found some quality patterns
	qualityFindings := 0
	for _, pattern := range qualityPatterns {
		if foundPatterns[pattern] {
			qualityFindings++
			t.Logf("✓ Found quality pattern: %s", pattern)
		} else {
			t.Logf("✗ Missing quality pattern: %s", pattern)
		}
	}

	if qualityFindings < 3 {
		t.Errorf("Expected to find at least 3 quality enforcement patterns, found %d", qualityFindings)
	}

	// Print all findings for debugging
	t.Logf("=== All findings ===")
	for _, finding := range findings {
		t.Logf("Pattern: %s, Line: %d, Content: %s", finding.Pattern, finding.Line, finding.Content)
	}
}

// TestQualityPatternsRealWorld tests quality patterns against realistic scenarios
func TestQualityPatternsRealWorld(t *testing.T) {
	// Remove local bundle override to ensure we use embedded patterns
	os.Remove(filepath.Join(os.Getenv("HOME"), ".atheon", "patterns.bundle"))
	testCases := []struct {
		name     string
		content  string
		expected []string
	}{
		{
			name: "Force git operations",
			content: `
#!/bin/bash
git push origin main --force
git reset --hard HEAD
git clean -fdx
`,
			expected: []string{"git-force-push", "git-hard-reset", "git-clean-force"},
		},
		{
			name: "Package manager shortcuts",
			content: `
npm install --force --legacy-peer-deps
pip install --ignore-installed package
bundle install --force
`,
			expected: []string{"build-force", "package-manager-force"},
		},
		{
			name: "Test skipping",
			content: `
mvn clean install -DskipTests
gradle test --skip-tests
pytest -k "not slow" --exitfirst
`,
			expected: []string{"skip-tests"},
		},
		{
			name: "Insecure connections",
			content: `
curl --insecure https://example.com
wget --no-check-certificate https://example.com
npm install --registry=http://insecure-registry.com
`,
			expected: []string{"insecure-flag"},
		},
		{
			name: "Auto-confirmation",
			content: `
apt-get install -y package
yes | pip install package
npm install --silent
`,
			expected: []string{"auto-confirm"},
		},
		{
			name: "Hook skipping",
			content: `
git commit --no-verify -m "skip hooks"
git push --no-verify
`,
			expected: []string{"skip-hooks"},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			testFile := filepath.Join(tmpDir, "test.txt")

			if err := os.WriteFile(testFile, []byte(tc.content), 0o644); err != nil {
				t.Fatal(err)
			}

			findings, _, err := core.ScanFile(testFile)
			if err != nil {
				t.Fatalf("ScanFile failed: %v", err)
			}

			// Check if expected patterns were found
			foundPatterns := make(map[string]bool)
			for _, finding := range findings {
				foundPatterns[finding.Pattern] = true
			}

			for _, expectedPattern := range tc.expected {
				if !foundPatterns[expectedPattern] {
					t.Errorf("Expected to find pattern '%s' but didn't", expectedPattern)
				}
			}

			// Log what we actually found
			t.Logf("Test case '%s' found %d patterns", tc.name, len(findings))
			for _, finding := range findings {
				t.Logf("  - %s: %s", finding.Pattern, strings.TrimSpace(finding.Content))
			}
		})
	}
}
